// <auto-generated />
namespace COURSE_CNTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Lan1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lan1));
        
        string IMigrationMetadata.Id
        {
            get { return "202304251032516_Lan1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
